version: '3'

services:
    db:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - "mongo:/data/db"

    genie:
        build: .
        ports:
            - "3000:3000"
            - "7547:7547"
        command: >
            bash -c ". /root/.nvm/nvm.sh &&
                    . /root/.nvm/bash_completion &&
                    (genieacs-cwmp &) &&
                    (genieacs-ui --ui-jwt-secret secret &) &&
                    tail -F anything"
        environment:
            - GENIEACS_MONGODB_CONNECTION_URL=mongodb://db:27017/genieacs
        depends_on:
            - db

volumes:
    mongo:
